

tbk_map = {
"it_pud" : "Italian-PUD",
"tr_imst" : "Turkish-IMST",
"kmr_mg" : "Kurmanji-MG",
"no_nynorsk" : "Norwegian-Nynorsk",
"pl_pdb" : "Polish-PDB",
"gun_thomas" : "Mbya_Guarani-Thomas",
"sk_snk" : "Slovak-SNK",
"it_twittiro" : "Italian-TWITTIRO",
"de_lit" : "German-LIT",
"fr_sequoia" : "French-Sequoia",
"en_lines" : "English-LinES",
"ga_idt" : "Irish-IDT",
"ca_ancora" : "Catalan-AnCora",
"es_pud" : "Spanish-PUD",
"pl_lfg" : "Polish-LFG",
"sms_giellagas" : "Skolt_Sami-Giellagas",
"eu_bdt" : "Basque-BDT",
"pt_bosque" : "Portuguese-Bosque",
"no_nynorsklia" : "Norwegian-NynorskLIA",
"en_ewt" : "English-EWT",
"is_pud" : "Icelandic-PUD",
"ru_syntagrus" : "Russian-SynTagRus",
"wo_wtb" : "Wolof-WTB",
"hsb_ufal" : "Upper_Sorbian-UFAL",
"cs_fictree" : "Czech-FicTree",
"la_perseus" : "Latin-Perseus",
"gun_dooley" : "Mbya_Guarani-Dooley",
"zh_hk" : "Chinese-HK",
"cs_cac" : "Czech-CAC",
"fa_seraji" : "Persian-Seraji",
"zh_pud" : "Chinese-PUD",
"it_isdt" : "Italian-ISDT",
"ug_udt" : "Uyghur-UDT",
"fro_srcmf" : "Old_French-SRCMF",
"gl_treegal" : "Galician-TreeGal",
"zh_gsd" : "Chinese-GSD",
"pl_pud" : "Polish-PUD",
"mdf_jr" : "Moksha-JR",
"gl_ctg" : "Galician-CTG",
"ar_pud" : "Arabic-PUD",
"sl_sst" : "Slovenian-SST",
"tr_gb" : "Turkish-GB",
"pt_gsd" : "Portuguese-GSD",
"fr_ftb" : "French-FTB",
"pt_pud" : "Portuguese-PUD",
"ta_ttb" : "Tamil-TTB",
"br_keb" : "Breton-KEB",
"ko_kaist" : "Korean-Kaist",
"bho_bhtb" : "Bhojpuri-BHTB",
"am_att" : "Amharic-ATT",
"mr_ufal" : "Marathi-UFAL",
"sr_set" : "Serbian-SET",
"el_gdt" : "Greek-GDT",
"en_gum" : "English-GUM",
"uk_iu" : "Ukrainian-IU",
"swl_sslc" : "Swedish_Sign_Language-SSLC",
"la_ittb" : "Latin-ITTB",
"grc_proiel" : "Ancient_Greek-PROIEL",
"grc_perseus" : "Ancient_Greek-Perseus",
"gd_arcosg" : "Scottish_Gaelic-ARCOSG",
"da_ddt" : "Danish-DDT",
"cu_proiel" : "Old_Church_Slavonic-PROIEL",
"fi_ftb" : "Finnish-FTB",
"got_proiel" : "Gothic-PROIEL",
"nl_lassysmall" : "Dutch-LassySmall",
"zh_cfl" : "Chinese-CFL",
"cs_pud" : "Czech-PUD",
"tr_pud" : "Turkish-PUD",
"koi_uh" : "Komi_Permyak-UH",
"ja_gsd" : "Japanese-GSD",
"be_hse" : "Belarusian-HSE",
"sv_pud" : "Swedish-PUD",
"id_pud" : "Indonesian-PUD",
"lv_lvtb" : "Latvian-LVTB",
"ja_modern" : "Japanese-Modern",
"fr_pud" : "French-PUD",
"ru_taiga" : "Russian-Taiga",
"en_gumreddit" : "English-GUMReddit",
"bg_btb" : "Bulgarian-BTB",
"lt_hse" : "Lithuanian-HSE",
"cs_pdt" : "Czech-PDT",
"orv_torot" : "Old_Russian-TOROT",
"es_ancora" : "Spanish-AnCora",
"nl_alpino" : "Dutch-Alpino",
"tl_trg" : "Tagalog-TRG",
"lt_alksnis" : "Lithuanian-ALKSNIS",
"sme_giella" : "North_Sami-Giella",
"vi_vtb" : "Vietnamese-VTB",
"en_pud" : "English-PUD",
"en_partut" : "English-ParTUT",
"de_pud" : "German-PUD",
"ro_rrt" : "Romanian-RRT",
"fi_pud" : "Finnish-PUD",
"ar_padt" : "Arabic-PADT",
"en_pronouns" : "English-Pronouns",
"he_htb" : "Hebrew-HTB",
"fr_gsd" : "French-GSD",
"bxr_bdt" : "Buryat-BDT",
"mt_mudt" : "Maltese-MUDT",
"te_mtg" : "Telugu-MTG",
"olo_kkpp" : "Livvi-KKPP",
"fr_fqb" : "French-FQB",
"fi_tdt" : "Finnish-TDT",
"sq_tsa" : "Albanian-TSA",
"cs_cltt" : "Czech-CLTT",
"et_ewt" : "Estonian-EWT",
"ru_pud" : "Russian-PUD",
"pcm_nsc" : "Naija-NSC",
"fr_spoken" : "French-Spoken",
"hu_szeged" : "Hungarian-Szeged",
"kpv_ikdp" : "Komi_Zyrian-IKDP",
"sa_vedic" : "Sanskrit-Vedic",
"it_partut" : "Italian-ParTUT",
"ko_pud" : "Korean-PUD",
"akk_pisandub" : "Akkadian-PISANDUB",
"yo_ytb" : "Yoruba-YTB",
"it_postwita" : "Italian-PoSTWITA",
"zh_gsdsimp" : "Chinese-GSDSimp",
"aii_as" : "Assyrian-AS",
"gsw_uzh" : "Swiss_German-UZH",
"ja_bccwj" : "Japanese-BCCWJ",
"krl_kkpp" : "Karelian-KKPP",
"ro_nonstandard" : "Romanian-Nonstandard",
"kpv_lattice" : "Komi_Zyrian-Lattice",
"fr_partut" : "French-ParTUT",
"ur_udtb" : "Urdu-UDTB",
"fo_oft" : "Faroese-OFT",
"en_esl" : "English-ESL",
"hi_hdtb" : "Hindi-HDTB",
"de_hdt" : "German-HDT",
"th_pud" : "Thai-PUD",
"yue_hk" : "Cantonese-HK",
"ja_pud" : "Japanese-PUD",
"sl_ssj" : "Slovenian-SSJ",
"la_llct" : "Latin-LLCT",
"et_edt" : "Estonian-EDT",
"kk_ktb" : "Kazakh-KTB",
"de_gsd" : "German-GSD",
"orv_rnc" : "Old_Russian-RNC",
"no_bokmaal" : "Norwegian-Bokmaal",
"id_gsd" : "Indonesian-GSD",
"ko_gsd" : "Korean-GSD",
"sv_lines" : "Swedish-LinES",
"ro_simonero" : "Romanian-SiMoNERo",
"cy_ccg" : "Welsh-CCG",
"tl_ugnayan" : "Tagalog-Ugnayan",
"hy_armtdp" : "Armenian-ArmTDP",
"hi_pud" : "Hindi-PUD",
"bm_crb" : "Bambara-CRB",
"lzh_kyoto" : "Classical_Chinese-Kyoto",
"ru_gsd" : "Russian-GSD",
"qhe_hiencs" : "Hindi_English-HIENCS",
"af_afribooms" : "Afrikaans-AfriBooms",
"la_proiel" : "Latin-PROIEL",
"ar_nyuad" : "Arabic-NYUAD",
"sv_talbanken" : "Swedish-Talbanken",
"it_vit" : "Italian-VIT",
"hr_set" : "Croatian-SET",
"sa_ufal" : "Sanskrit-UFAL",
"wbp_ufal" : "Warlpiri-UFAL",
"es_gsd" : "Spanish-GSD",
"cop_scriptorium" : "Coptic-Scriptorium",
"myv_jr" : "Erzya-JR"
}


chunk_deps = {"NP" : { "primary" : {"amod" : [],
                                    "amod:attlvc" : [],
                                    "amod:mode" : [],
                                    "amod:obl" : [],
                                    "amod:att" : [],
                                    "clf" : [],
                                    "compound:nn" : [],
                                    "det" : [],
                                    "det:def" : [],
                                    "det:numgov" : [],
                                    "det:nummod" : [],
                                    "det:poss" : [],
                                    "det:predet": [],
                                    "det:quant": [],
                                    "flat" : [],
                                    "flat:name" : [],
                                    "flat:foreign" : [],
                                    "flat:repeat" : [],
                                    "flat:title" : [],
                                    "fixed" : [],
                                    "goeswith" : [],
                                    "nmod:poss" : ["PRON"],
                                    "nummod" : [],
                                    "nummod:entity" : [],
                                    "nummod:gov": [],
                                    },
                       "secondary" : {"acl" : [],
                                    "advmod" : [],
                                    "advmod:discourse" : [],
                                    "advmod:emph" : [],
                                    "advmod:quant" : [],
                                    "appos" : [],
                                    "conj" : [],
                                    "compound" : [],
                                    "compound:plur" : [],
                                    "compound:prt" : [],
                                    "compound:redup" : [],
                                    "compound:smixut" : [],
                                    "dep": [],
                                    "mark:prt": [],
                                    "nmod" : [],
                                    "nmod:abl" : [],
                                    "nmod:agent": [],
                                    "nmod:arg" : [],
                                    "nmod:att" : [],
                                    "nmod:attlvc" : [],
                                    "nmod:cau" : [],
                                    "nmod:clas" : [],
                                    "nmod:comp": [],
                                    "nmod:cmp" : [],
                                    "nmod:dat" : [],
                                    "nmod:gobj" : [],
                                    "nmod:gmod": [],
                                    "nmod:gsubj": [],
                                    "nmod:obl" : [],
                                    "nmod:obllvc" : [],
                                    "nmod:own" : [],
                                    "nmod:npmod" : [],
                                    "nmod:part": [],
                                    "nmod:pmod" : [],
                                    "nmod:ref": [],
                                    "nmod:tmod" : [],
                                    "obl" : [],
                                    "obl:agent": [],
                                    "obl:arg" : [],
                                    "obl:cau" : [],
                                    "obl:npmod" : [],
                                    "obl:own" : [],
                                    "obl:patient": [],
                                    "obl:tmod" : [],
                                    "punct" : []
                                    }
                    },
              "VP" : { "primary" : {},
                       "secondary" : {"advmod" : [],
                                    "advmod:discourse" : [],
                                    "advmod:df": [],
                                    "advmod:emph" : [],
                                    "advmod:locy" : [],
                                    "advmod:neg" : [],
                                    "advmod:obl": [],
                                    "advmod:tlocy": [],
                                    "advmod:tmod" : [],
                                    "advmod:to" : [],
                                    "advmod:tto" : [],
                                    "aux" : [],
                                    "aux:caus" : [],
                                    "aux:neg" : [],
                                    "aux:pass" : [],
                                    "aux:q" : [],
                                    "advcl" : [],
                                    "ccomp" : [],
                                    "compound:conjv" : [],
                                    "compound:dir" : [],
                                    "compound:ext" : [],
                                    "compound:lvc" : [],
                                    "compound:preverb" : [],
                                    "compound:prt" : [],
                                    "compound:redup" : [],
                                    "compound:svc" : [],
                                    "compound:vo" : [],
                                    "compound:vv" : [],
                                    "conj:extend": [],
                                    "cop" : [],
                                    "dep": [],
                                    "det": [],
                                    "fixed": [],
                                    "goeswith": [],
                                    "mark": ["PART"],
                                    "mark:adv": ["PART"],
                                    "mark:advb": ["PART"],
                                    "mark:comp" : ["PART"],
                                    "mark:prt" : ["PART"],
                                    "mark:relcl" : ["PART"],
                                    "mark:rel" : ["PART"],
                                    "obl": [],
                                    "obl:loc": [],
                                    "obl:prep": [],
                                    "punct" : [],
                                    "root" : [],
                                    "xcomp" : []
                                    }
                    },
              "ADVP" : {"primary" : {"fixed" : [],
                                    "goeswith": []
                                    },
                        "secondary" : {"advmod" : [],
                                    "advmod:discourse": [],
                                    "advmod:emph" : [],
                                    "advmod:locy": [],
                                    "advmod:tmod": [],
                                    "advmod:to" : [],
                                    "advmod:tto" : [],
                                    }
                    },
              "ADJP" : {"primary" : {"det" : [],
                                    "fixed": [],
                                    "goeswith": [],
                                    "nummod" : []
                                    },
                        "secondary" : {"advmod" : [],
                                    "advmod:discourse": [],
                                    "advmod:emph" : [],
                                    "advmod:locy" : [],
                                    "advmod:tmod" : [],
                                    "advmod:to" : [],
                                    "advmod:tto": [],
                                    "compound:redup": [],
                                    "mark:advb": ["PART"],
                                    "mark:comp" : ["PART"],
                                    "mark:prt": [],
                                    "mark:rel": ["PART"],
                                    "mark:relcl": ["PART"],
                                    "obl:npmod" : [],
                                    },
                    },
              "PP": {"primary" : {"fixed" : [],
                                "goeswith": []
                                },
                     "secondary" : {"advmod:tmod": [],
                                }
                    },
              "CONJ": {"primary" : {"fixed" : [],
                                    "goeswith": []
                                    },
                    "secondary" : {}
                        },
}

numerical_symbol = ["$", "%", "£", "°", "€", "n°", "kw", "kg", "g", "km", "cm", "mm", "m", "m²", "cm²", "mm²", "km²"]